### ISSUE TITLE
How should I use protoc-gen-force-jsonrpc in my project?

### ISSUE THREAD

**Issue by kscooo** [ipfs-force-community/gosf#4]
![image](https://user-images.githubusercontent.com/27288263/86700546-c6ddfc00-c043-11ea-8a5e-e41553db6b0a.png)

As you can see, I've downloaded the protoc-gen-force-jsonrpc binary in the go/bin directory, but I'm not sure how to use protoc command to generate the corresponding pb.go file

**Comment by kscooo** [comment]
protoc --go_out=plugins=protoc-gen-force-jsonrpc: filscanproto.proto

--go_out: protoc-gen-go: unknown plugin "protoc-gen-force-jsonrpc"

**Comment by kscooo** [comment]
protoc --plugin=protoc-gen-force-jsonrpc=./protoc-gen-force-jsonrpc --force-jsonrpc_out=. filscanproto.proto

but it's not i except file

**Comment by eval-exec** [comment]
> protoc --plugin=protoc-gen-force-jsonrpc=./protoc-gen-force-jsonrpc --force-jsonrpc_out=. filscanproto.proto
> 
> but it's not i except file

Have you solve this problem? how you do that ?
